name: library

services:
  postgres:
    container_name: postgres
    image: postgres:14
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library-db
    volumes:
      - "./local-config/00_setupdb.sql:/docker-entrypoint-initdb.d/00_setupdb.sql"
      - "./local-config/01_populate.sql:/docker-entrypoint-initdb.d/01_populatedb.sql"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

  database-acl:
    container_name: database-acl
    build: ./database-acl/
    network_mode: host
    ports:
      - "50051:50051"
    environment:
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_PWD=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  library-backend:
    container_name: library-backend
    build: ./library-backend/
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - DB_ACL_HOST=localhost
      - DB_ACL_PORT=50051
    depends_on:
      - database-acl
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
