INSERT INTO album (title, artist, price) VALUES
    ('The Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Thriller', 'Michael Jackson', 14.99),
    ('Back in Black', 'AC/DC', 15.99),
    ('The Wall', 'Pink Floyd', 18.99),
    ('Abbey Road', 'The Beatles', 17.99),
    ('Rumours', 'Fleetwood Mac', 16.99),
    ('Hotel California', 'Eagles', 17.49),
    ('21', 'Adele', 13.99),
    ('The Eminem Show', 'Eminem', 15.49),
    ('Born to Run', 'Bruce Springsteen', 16.49),
    ('The Joshua Tree', 'U2', 14.99),
    ('Darkness on the Edge of Town', 'Bruce Springsteen', 16.99),
    ('A Night at the Opera', 'Queen', 18.49),
    ('Led Zeppelin IV', 'Led Zeppelin', 19.49),
    ('Sgt. Peppers Lonely Hearts Club Band', 'The Beatles', 17.99),
    ('OK Computer', 'Radiohead', 16.99),
    ('London Calling', 'The Clash', 15.99),
    ('The Chronic', 'Dr. Dre', 14.49),
    ('Back to Black', 'Amy Winehouse', 16.49),
    ('In the Aeroplane Over the Sea', 'Neutral Milk Hotel', 15.49),
    ('The Best of The Doors', 'The Doors', 13.99),
    ('Hotel Rwanda', 'Various Artists', 14.99),
    ('No Strings Attached', '*NSYNC', 12.99),
    ('Meteora', 'Linkin Park', 17.99),
    ('Future Nostalgia', 'Dua Lipa', 18.49),
    ('Fine Line', 'Harry Styles', 17.99),
    ('The Fame Monster', 'Lady Gaga', 14.99),
    ('Lemonade', 'Beyoncé', 19.99),
    ('Future Nostalgia', 'Dua Lipa', 18.49),
    ('Revolver', 'The Beatles', 16.99),
    ('The Miseducation of Lauryn Hill', 'Lauryn Hill', 15.99),
    ('Blackstar', 'David Bowie', 19.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('The Life of Pablo', 'Kanye West', 16.49),
    ('The College Dropout', 'Kanye West', 15.49),
    ('Rumours', 'Fleetwood Mac', 16.99),
    ('American Idiot', 'Green Day', 13.99),
    ('A Rush of Blood to the Head', 'Coldplay', 18.49),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('High as Hope', 'Florence + The Machine', 17.49),
    ('Reckless', 'Lindsay Ell', 15.99),
    ('Love for Sale', 'Lady Gaga and Tony Bennett', 14.99),
    ('Justice', 'Justin Bieber', 18.49),
    ('Life Support', 'Madison Beer', 16.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Evermore', 'Taylor Swift', 17.99),
    ('Love Songs', 'Various Artists', 15.49),
    ('30', 'Adele', 19.99),
    ('Courage to Love', 'Various Artists', 14.99),
    ('Ghost Stories', 'Coldplay', 16.99),
    ('Rumours', 'Fleetwood Mac', 16.99),
    ('The Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Thriller', 'Michael Jackson', 14.99),
    ('Back in Black', 'AC/DC', 15.99),
    ('The Wall', 'Pink Floyd', 18.99),
    ('Abbey Road', 'The Beatles', 17.99),
    ('Rumours', 'Fleetwood Mac', 16.99),
    ('Hotel California', 'Eagles', 17.49),
    ('21', 'Adele', 13.99),
    ('The Eminem Show', 'Eminem', 15.49),
    ('Born to Run', 'Bruce Springsteen', 16.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('High as Hope', 'Florence + The Machine', 17.49),
    ('Reckless', 'Lindsay Ell', 15.99),
    ('Love for Sale', 'Lady Gaga and Tony Bennett', 14.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Justice', 'Justin Bieber', 18.49),
    ('Life Support', 'Madison Beer', 16.99),
    ('Evermore', 'Taylor Swift', 17.99),
    ('Love Songs', 'Various Artists', 15.49),
    ('30', 'Adele', 19.99),
    ('Courage to Love', 'Various Artists', 14.99),
    ('Ghost Stories', 'Coldplay', 16.99),
    ('Rumours', 'Fleetwood Mac', 16.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('The Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('The Joshua Tree', 'U2', 14.99),
    ('Darkness on the Edge of Town', 'Bruce Springsteen', 16.99),
    ('A Night at the Opera', 'Queen', 18.49),
    ('Led Zeppelin IV', 'Led Zeppelin', 19.49),
    ('Sgt. Peppers Lonely Hearts Club Band', 'The Beatles', 17.99),
    ('OK Computer', 'Radiohead', 16.99),
    ('London Calling', 'The Clash', 15.99),
    ('The Chronic', 'Dr. Dre', 14.49),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Back to Black', 'Amy Winehouse', 16.49),
    ('In the Aeroplane Over the Sea', 'Neutral Milk Hotel', 15.49),
    ('The Best of The Doors', 'The Doors', 13.99),
    ('Hotel Rwanda', 'Various Artists', 14.99),
    ('No Strings Attached', '*NSYNC', 12.99),
    ('Meteora', 'Linkin Park', 17.99),
    ('Future Nostalgia', 'Dua Lipa', 18.49),
    ('Fine Line', 'Harry Styles', 17.99),
    ('The Fame Monster', 'Lady Gaga', 14.99),
    ('Lemonade', 'Beyoncé', 19.99),
    ('Future Nostalgia', 'Dua Lipa', 18.49),
    ('Revolver', 'The Beatles', 16.99),
    ('The Miseducation of Lauryn Hill', 'Lauryn Hill', 15.99),
    ('Blackstar', 'David Bowie', 19.99),
    ('The Life of Pablo', 'Kanye West', 16.49),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('The College Dropout', 'Kanye West', 15.49),
    ('Rumours', 'Fleetwood Mac', 16.99),
    ('American Idiot', 'Green Day', 13.99),
    ('A Rush of Blood to the Head', 'Coldplay', 18.49),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('High as Hope', 'Florence + The Machine', 17.49),
    ('Reckless', 'Lindsay Ell', 15.99),
    ('Love for Sale', 'Lady Gaga and Tony Bennett', 14.99),
    ('Justice', 'Justin Bieber', 18.49),
    ('Life Support', 'Madison Beer', 16.99),
    ('Evermore', 'Taylor Swift', 17.99),
    ('Love Songs', 'Various Artists', 15.49),
    ('30', 'Adele', 19.99),
    ('Courage to Love', 'Various Artists', 14.99),
    ('Come Away With Me', 'Norah Jones', 14.99),
    ('Dark Side of the Moon', 'Pink Floyd', 19.99),
    ('Viva La Vida', 'Coldplay', 17.49),
    ('Beyoncé', 'Beyoncé', 18.99),
    ('Born to Die', 'Lana Del Rey', 15.49),
    ('The Marshall Mathers LP', 'Eminem', 16.99),
    ('Mammoth WVH', 'Mammoth WVH', 14.99),
    ('Legends Never Die', 'Juice WRLD', 18.99),
    ('After Hours', 'The Weeknd', 17.99),
    ('Folklore', 'Taylor Swift', 16.99),
    ('Evermore', 'Taylor Swift', 16.99),
    ('Cuz I Love You', 'Lizzo', 14.99),
    ('Invasion of Privacy', 'Cardi B', 15.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 17.49),
    ('Channel Orange', 'Frank Ocean', 16.49),
    ('Astroworld', 'Travis Scott', 18.49),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 15.99),
    ('Lover', 'Taylor Swift', 14.99),
    ('folklore', 'Taylor Swift', 16.49),
    ('Views', 'Drake', 17.49),
    ('Take Care', 'Drake', 15.99),
    ('Lemonade', 'Beyoncé', 18.49),
    ('The Gift', 'Beyoncé', 16.99),
    ('Hozier', 'Hozier', 14.99),
    ('Currents', 'Tame Impala', 15.49),
    ('Damn', 'Kendrick Lamar', 17.99),
    ('The 20/20 Experience', 'Justin Timberlake', 16.49),
    ('Purpose', 'Justin Bieber', 14.99),
    ('American Beauty/American Psycho', 'Fall Out Boy', 15.99),
    ('Future', 'Future', 17.99),
    ('Blonde', 'Frank Ocean', 16.49),
    ('Nothing Was the Same', 'Drake', 18.49),
    ('If I Know Me', 'Mike Morgan', 14.99),
    ('Reputation', 'Taylor Swift', 16.99),
    ('Kamikaze', 'Eminem', 15.49),
    ('Certified Lover Boy', 'Drake', 19.99),
    ('SOUR', 'Olivia Rodrigo', 17.99),
    ('Smile', 'Katy Perry', 16.99),
    ('Purpose', 'Justin Bieber', 15.49),
    ('Fearless (Taylors Version)', 'Taylor Swift', 18.99),
    ('Red (Taylors Version)', 'Taylor Swift', 16.49),
    ('30', 'Adele', 19.99),
    ('Ghost Stories', 'Coldplay', 16.99),
    ('Rumours', 'Fleetwood Mac', 16.99);
